require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'gemfiles/**/*'

Layout/LineLength:
  Max: 190

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

RSpec/NestedGroups:
  Enabled: false
