AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'gemfiles/**/*'

Layout/LineLength:
  Max: 190

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
