language: ruby
cache: bundler
sudo: false

gemfile:
  - gemfiles/rails_6.gemfile
  - gemfiles/rails_7.gemfile
  - gemfiles/rails_8.gemfile

rvm:
  - 3.2
  - 3.3
  - 3.4
  - 4.0

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - mkdir ./tmp/
  - bundle exec rubocop
  - bundle exec rspec
