language: ruby
cache: bundler
sudo: false

gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
  - gemfiles/rails_7.gemfile

rvm:
  - 2.6
  - 2.7
  - 3.0
  - 3.1

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - mkdir ./tmp/
  - bundle exec rubocop
  - bundle exec rspec

matrix:
  exclude:
    # rails 7 requires ruby > 2.7
    - rvm: 2.6
      gemfile: gemfiles/rails_7.gemfile
    # rails 5 is too old for these ruby versions
    - rvm: 2.7
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 3.0
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 3.1
      gemfile: gemfiles/rails_5.gemfile
  fast_finish: true
